%%
%% This is file `fdumath-article.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% fdumath.dtx  (with options: `class,article')
%% 
%%     Copyright (C) 2022--2023
%%     School of Mathematical Sciences, Fudan University,
%%     Shanghai Center for Mathematical Sciences, Fudan University,
%%     and any individual authors listed in the documentation.
%% ---------------------------------------------------------------------
%% 
%%     This work may be distributed and/or modified under the
%%     conditions of the LaTeX Project Public License, either
%%     version 1.3c of this license or (at your option) any later
%%     version. This version of this license is in
%%        http://www.latex-project.org/lppl/lppl-1-3c.txt
%%     and the latest version of this license is in
%%        http://www.latex-project.org/lppl.txt
%%     and version 1.3 or later is part of all distributions of
%%     LaTeX version 2005/12/01 or later.
%% 
%%     This work has the LPPL maintenance status "maintained".
%% 
%% ---------------------------------------------------------------------
%% 
%% 
%%     This package consists of the files fdumath.dtx,
%%                  and the derived files fdumath.ins,
%%                                        fdumath-article.cls,
%%                                        fdumath-exercise.cls,
%%                                        fdumath-assignment.cls,
%%                                        fdumath-exam.cls,
%%                                        fdumath-thesis.cls,
%%                                        fdumath-book.cls,
%%                                        fdumath-report.cls,
%%                                        fdumath-beamer.cls, and
%%                                        README.md.
%%
%% End of file `fdumath-article.cls'.
